### ISSUE TITLE
Unity 2019.3.X HDRP not working

### ISSUE THREAD

**Issue by aiden-beltran** [keijiro/KinoGlitch#12]
We recently downloaded the project and tried attaching the digital glitch script to our main camera in our intro scene but we didn’t get an effect. We are currently on unity 2019.3.7 and are on the most up to date HDRP version as of April 24,2020.

**Comment by keijiro** [comment]
KinoGlitch doesn't support any SRP (UWP/HDRP).

You can use Kino instead. It contains a glitch effect that is almost identical to KinoGlitch.

https://github.com/keijiro/Kino
