### ISSUE TITLE
Not Wotking with Post Processing

### ISSUE THREAD

**Issue by Vardan2009** [keijiro/KinoGlitch#14]
When I add  Analog glitch the game becomes black, but when I remove post processing the glitch works
Now I Need Both Post Processing and Glitch effect
Plz help

**Comment by keijiro** [comment]
Do you mean Unity's Post Processing Stack? Which version?

**Comment by Vardan2009** [comment]
Yes @keijiro , Unity's Post Processing Stack

Lastest Version

I'm Using Unity 2020.1.7f1 Personal

Here is the Post Processing from Package Manager:

![bandicam 2020-10-26 11-28-16-391](https://user-images.githubusercontent.com/70532109/97144843-9ea71400-177e-11eb-9cdd-46944a2a2fe2.jpg)

**Comment by keijiro** [comment]
Are you using the legacy (built-in) render pipeline? Or Universal Render Pipeline?

**Comment by Vardan2009** [comment]
What is Render Pipeline?
Sorry

**Comment by Vardan2009** [comment]
im using legacy (built-in) render pipeline

**Comment by keijiro** [comment]
I haven't used PPS on the legacy render pipeline for years, so actually, I have no idea about what's happening in it.

**Comment by Vardan2009** [comment]
ok, so I'm gonna close this issue :/
