### ISSUE TITLE
Not working with my project

### ISSUE THREAD

**Issue by Josh65-2201** [keijiro/KinoGlitch#16]
I'm using unity 2020.1.6f1 and the HDRP for the rendering pipeline. When i use the test project provided it works fine but when i put them on my camera in my project it doesn't work at all. And I've tried making a blank camera and putting both of them on there. i'm really not sure why it doesn't work.

**Comment by keijiro** [comment]
Image effects are not compatible with scriptable render pipelines (URP/HDRP). You can use the Kino suite for HDRP instead: https://github.com/keijiro/Kino
