### ISSUE TITLE
12 Errors on import

### ISSUE THREAD

**Issue by Timtendo12** [keijiro/KinoGlitch#18]
Hi! I just imported this amazing asset only it gives me 12 errors after importing it.

1.Assets\Kino\Glitch\AnalogGlitch.cs(30,18): error CS0101: The namespace 'Kino' already contains a definition for 'AnalogGlitch'

2.Assets\Kino\Glitch\DigitalGlitch.cs(111,14): error CS0111: Type 'DigitalGlitch' already defines a member called 'OnRenderImage' with the same parameter types

3. Assets\Kino\Glitch\DigitalGlitch.cs(27,6): error CS0579: Duplicate 'ExecuteInEditMode' attribute

4. Assets\Kino\Glitch\DigitalGlitch.cs(29,6): error CS0579: Duplicate 'AddComponentMenu' attribute

5.  Assets\Kino\Glitch\AnalogGlitch.cs(27,6): error CS0579: Duplicate 'ExecuteInEditMode' attribute

6.  Assets\Kino\Glitch\AnalogGlitch.cs(29,6): error CS0579: Duplicate 'AddComponentMenu' attribute

7. Assets\Kino\Glitch\AnalogGlitch.cs(88,14): error CS0111: Type 'AnalogGlitch' already defines a member called 'OnRenderImage' with the same parameter types

8. Assets\Kino\Glitch\DigitalGlitch.cs(57,22): error CS0111: Type 'DigitalGlitch' already defines a member called 'RandomColor' with the same parameter types

9. Assets\Kino\Glitch\DigitalGlitch.cs(62,14): error CS0111: Type 'DigitalGlitch' already defines a member called 'SetUpResources' with the same parameter types

10. Assets\Kino\Glitch\DigitalGlitch.cs(111,14): error CS0111: Type 'DigitalGlitch' already defines a member called 'OnRenderImage' with the same parameter types

11. Assets\Kino\Glitch\DigitalGlitch.cs(102,14): error CS0111: Type 'DigitalGlitch' already defines a member called 'Update' with the same parameter types

12. Assets\Kino\Glitch\DigitalGlitch.cs(111,14): error CS0111: Type 'DigitalGlitch' already defines a member called 'OnRenderImage' with the same parameter types

Im using: Unity 2021.1.6f1 DX11 ~ Univeral Render Pipeline

Idk if these are easy fixes. I have no experience in C#.  Could you take a look at it?

**Comment by keijiro** [comment]
This effect was developed 6 years ago. There was no URP at that point. It's only compatible with the legacy (built-in) render pipeline.
