### ISSUE TITLE
Colors shift colors

### ISSUE THREAD

**Issue by tomihr** [keijiro/KinoGlitch#19]
Hello, can I maybe specify colors for the color shift effect?

**Comment by keijiro** [comment]
What did you mean?

**Comment by tomihr** [comment]
Now when using the analog color drift effect image splits to green and purple, I need to break in green and orange, or maybe to be able to change the color is that possible?

**Comment by keijiro** [comment]
It splits colors into the R-G-B primaries and displaces G and RB with different values.

Green and orange can't be color primaries (the R component is missing). So, it wouldn't work.

**Comment by keijiro** [comment]
I'm closing this issue now. Please reopen it for further problems.
