### ISSUE TITLE
Force Close Android Device

### ISSUE THREAD

**Issue by nndwn** [keijiro/KinoGlitch#22]
I was trying to build a test on an Android device, when suddenly it force closed. I tried to figure out the cause by disabling some scripts I had created earlier, and I found out when I tried to deactivate the AnalogGlitch script, the force close didn't occur. I tried to find out the reason why because I felt this script was just simple. After examining it, I found out that this was the cause:

[ExecuteInEditMode]

After removing it, everything ran smoothly.

I don't know why, but I tried and made sure again. Suddenly, it force closes when adding it back, i put this script in singleton camera

btw im put  in credit your name you prefer username or your real name ?

![WhatsApp Image 2024-04-17 at 15 20 54](https://github.com/keijiro/KinoGlitch/assets/25237268/7e292ae1-abc4-4d8e-926b-bddf5d21ad7c)

**Comment by keijiro** [comment]
`[ExecuteInEditMode]` doesn't have any effect in Play Mode, so it shouldn't be relevant.

Nevertheless, if it solved your issue, it should be removed on your side anyway.

Regarding the credit, either is okay.
