### ISSUE TITLE
Unity 6 compatability

### ISSUE THREAD

**Issue by Screamycat** [keijiro/KinoGlitch#23]
It seems though as for the newer versions of unity, or rather the newest version being unity 6, errors appear that I myself have tried to fix with no avail. I would love a updated version of this repo as I have not found anything greater than this effect!

**Comment by keijiro** [comment]
It should work with the built-in render pipeline.

(It doesn't support URP)

**Comment by Screamycat** [comment]
Yes, I am terribly sorry! I was meant to open an issue on this repo: https://github.com/saimarei/URPGlitch

**Comment by keijiro** [comment]
Okay, I close this issue.
