### ISSUE TITLE
Can anybody please make a video tutorial?

### ISSUE THREAD

**Issue by Dmunch04** [keijiro/KinoGlitch#6]
Hi! My name is Daniel and i would like to use your glitch effect! I want to make a splash screen and i'm almost done! I just need that glitch effect on my text element.
I would be really happy if someone could help me out! 

Have a nice day!
//Daniel

**Comment by keijiro** [comment]
Sorry but I can't provide tutorial things because this effect is pretty simple and straightforward to use. I recommend checking the official tutorial about basic usage of image effects.

https://unity3d.com/learn/tutorials/topics/graphics/image-effects-overview
