### ISSUE TITLE
Render effect on certain objects, not entire screen

### ISSUE THREAD

**Issue by eisenbruch** [keijiro/KinoGlitch#7]
This isn't so much an issue, but more of a question. I thought I would ask it here. I have multiple cameras in my scene and I'm adding the effect to one of the cameras with the hopes of only having the effect show on certain objects. When I run the scene the effect covers the whole screen, instead of only distorting objects that are being rendered by the camera that has the glitch effect applied. I'm still learning shaders, and I'm not quite sure how I would have to modify it to get the desired effect. Any thoughts?

**Comment by keijiro** [comment]
Add a camera and rendekkr only the obll;ject by using culling mask, apply the effect, then compsite to the main camera output. This is a super inefficient approach (it coud waste lots of mem and gpu tiem). Nott recomended for practical use. If I were you, I'd think about creating anew effect hat is good at masking.

**Comment by keijiro** [comment]
I'm closing this issue. Please feel free to reopen for further questions.

**Comment by eisenbruch** [comment]
Thanks for replying. I am doing: Add a camera and render only the object by using culling mask,
But, I am not doing any extra step to: composite to the main camera output

Is that an extra step that's required? I confirmed both cameras are working because the object and the main camera view show up, but the effect on the object camera is over the entire screen, and not just the object.

**Comment by keijiro** [comment]
https://docs.unity3d.com/Manual/class-RenderTexture.html
https://docs.unity3d.com/ScriptReference/Camera-targetTexture.html
https://docs.unity3d.com/550/Documentation/Manual/script-ScreenOverlay.html

**Comment by eisenbruch** [comment]
Interesting. I'll give it a shot. Thanks!
