### ISSUE TITLE
HDRP support?

### ISSUE THREAD

**Issue by davoodkharmanzar** [keijiro/KinoGlitch#9]
hello,
does it support on HDRP with PP stack v2 ?

thanks.

**Comment by keijiro** [comment]
No. It should be re-implemented as a custom effect for the post-processing stack, like this https://github.com/keijiro/Kino

**Comment by keijiro** [comment]
I'm closing this ticket. Please feel free to reopen for further questions.

**Comment by davoodkharmanzar** [comment]
seems that kino is for 2018.3 and later ...
so ... can i implement Glitch for 2018.2?
i'm using the custom version of HDRP of **[Book of the Dead](https://assetstore.unity.com/packages/essentials/tutorial-projects/book-of-the-dead-environment-121175)** unity project ...

**Comment by keijiro** [comment]
Actually not so difficult. At the moment it only support 2018.3 and later, but you can use it with small modifications (changing shader include paths).

**Comment by davoodkharmanzar** [comment]
thanks ... but my shading knowledge is poor :[

Glitch is CG shader ... the Kino collection is HLSL shader ...
so, can you update glitch for HDRP with that small modifications  please?
